### ISSUE TITLE
Cannot update to the latest version 1.0.0-m1

### ISSUE THREAD

**Issue by jherkel** [joschi/asdf-mvnd#7] opened 2022-12-22 17:42 UTC
I tried to update to the latest version of mvnd but with no success

1) Command asdf latest mvnd returns 1.0.0-m1
2) After  asdf install mvnd latest I can see this output : 
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     16      0 --:--:-- --:--:-- --:--:--     0
[/tmp/mvnd_tcISi94/mvnd-1.0.0-m1.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/mvnd_tcISi94/mvnd-1.0.0-m1.zip or
        /tmp/mvnd_tcISi94/mvnd-1.0.0-m1.zip.zip, and cannot find /tmp/mvnd_tcISi94/mvnd-1.0.0-m1.zip.ZIP, period.
asdf-mvnd error:  failed to extract mvnd archive
`

**Comment by joschi** [comment] 2022-12-22 22:00
@jherkel Thanks for reporting this!

Could this be a duplicate of #6?

**Comment by joschi** [comment] 2022-12-22 22:26
@jherkel Could you please try the latest version of the plugin?

**Closed as completed** 2022-12-22 22:26 UTC
Labels: bug

**Comment by jherkel** [comment] 2022-12-23 18:42
I tried it, it works. Thanks
